### ISSUE TITLE
Update AtarPathfindingProject 5.0.9. Import error

### ISSUE THREAD

**Issue by promiselonely** [recast4j/recast4j#189]
![xx](https://github.com/recast4j/recast4j/assets/3787092/895d8513-2730-44de-91c8-fe86a33907bf)

**Comment by ppiastucki** [comment]
I would be grateful if you could attach an example zip file to this ticket.

**Comment by promiselonely** [comment]
I guess it's because of this：

![1](https://github.com/recast4j/recast4j/assets/3787092/95146fd7-4252-4ae2-bb9a-910a11615ffd)
![2](https://github.com/recast4j/recast4j/assets/3787092/953d68d1-a197-4d40-bfe5-824176b2bef9)
[116.zip](https://github.com/recast4j/recast4j/files/15156920/116.zip)
