### ISSUE TITLE
How can I directly save and load the build result of a DynamicNavMesh

### ISSUE THREAD

**Issue by OhJeongrok** [recast4j/recast4j#208]
When using the Recast4j library, even after saving and loading a VoxelFile, I still need to perform a full tile build at least once to properly use the DynamicNavMesh. 

However, when the map is large, this initial build process takes a considerable amount of time.
I'd like to know how I can save the results of this build process and load them later to avoid the long build time.
While I don't necessarily need code examples, I'd appreciate guidance on the implementation approach or any relevant keywords to explore.

**Comment by ppiastucki** [comment]
The necessary changes can be found here: https://github.com/recast4j/recast4j/pull/209/files. Please see the included test for more information on how to use the functionality. Let me know if it fits your needs before I merge it.
